name: CI Workflow

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: 빌드 및 테스트
        run: ./gradlew build

      - name: Docker 빌드
        run: docker build -t myapp:latest .

      - name: 커밋 해시 태그 설정
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t myapp:$IMAGE_TAG .
